#!/bin/bash
FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"
is_docker_running () {
    # Visor 是多服务栈, 我们只关心 ui 这个对外服务是不是 running
    docker inspect visor-ui 2>/dev/null | grep -q "\"Status\": \"running\"," || exit 1
    return
}
case $1 in
start) exit 0 ;;
stop) exit 0 ;;
status) if is_docker_running; then exit 0; else exit 3; fi ;;
*) exit 1 ;;
esac
